//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgelTraining.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionInExam
    {
        public int IDExamen { get; set; }
        public int IDPregunta { get; set; }
        public string Respuesta { get; set; }
        public string Matricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Examan Examan { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
