//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgelTraining.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasErronea
    {
        public int Consecutivo { get; set; }
        public int ID_Pregunta { get; set; }
        public string Opcion { get; set; }
        public string TextoRespuesta { get; set; }
        public string Explicacion { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
    }
}
